### ISSUE TITLE
invalid dependency when converting from Graphx

### ISSUE THREAD

**Issue by srooznow** [graphframes/graphframes#109] opened 2016-09-14 16:39 UTC
scala version 2.11.7
spark-2.0.0-bin-hadoop2.7
graphframes-0.2.0-spark2.0-s_2.11.jar
```
$ ./bin/spark-shell --master local[4] --jars /Downloads/graphframes-0.2.0-spark2.0-s_2.11.jar
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
16/09/14 09:29:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/09/14 09:29:38 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Spark context Web UI available at http://10.0.1.26:4040
Spark context available as 'sc' (master = local[4], app id = local-1473870577895).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.0
      /_/
         
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.graphframes._
import org.graphframes._

scala> import org.apache.spark.graphx._
import org.apache.spark.graphx._

scala> import org.apache.spark.graphx.util.GraphGenerators
import org.apache.spark.graphx.util.GraphGenerators

scala> import org.apache.spark.rdd.RDD
import org.apache.spark.rdd.RDD

scala> val myVertices = sc.makeRDD(Array((1L, "Ann"),(2L, "Bill"),(3L, "Charles"),(4L, "Diane"),(5L, "Went to gym this morning")))
myVertices: org.apache.spark.rdd.RDD[(Long, String)] = ParallelCollectionRDD[0] at makeRDD at <console>:32

scala> val myEdges = sc.makeRDD(Array(Edge(1L, 2L, "is-friends-with"),Edge(2L, 3L, "is-friends-with"),Edge(3L, 4L, "is-friends-with"),Edge(4L, 5L, "Likes-status"),Edge(3L, 5L, "Wrote-status")))
myEdges: org.apache.spark.rdd.RDD[org.apache.spark.graphx.Edge[String]] = ParallelCollectionRDD[1] at makeRDD at <console>:32

scala> val myGraph = Graph(myVertices, myEdges)
myGraph: org.apache.spark.graphx.Graph[String,String] = org.apache.spark.graphx.impl.GraphImpl@38f3dbbf

scala> val gf = GraphFrame.fromGraphX(myGraph)
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term scalalogging in value com.typesafe,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.typesafe.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access type LazyLogging in value com.slf4j,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.slf4j.
```

**Comment by jkbradley** [comment] 2016-09-29 00:06
Thanks for reporting this!  I was able to reproduce it locally, though I found it works in Databricks.  I'll look into it.

**Comment by felixcheung** [comment] 2016-09-29 00:17
it looks like it can't resolve `com.typesafe.scalalogging`

**Comment by sbromberger** [comment] 2016-10-03 22:01
Actually, I'm having the same problem here within `spark-shell`:


```
$ spark-shell --master local[4] --jars graphframes-0.2.0-spark2.0-s_2.11.jar ~/.m2/repository/com/typesafe/scala-logging/scala-logging-slf4j_2.11/2.1.2/scala-logging-slf4j_2.11-2.1.2.jar
...


scala> val v = sc.parallelize(List(1,2,3,4,5)).toDF("id")
v: org.apache.spark.sql.DataFrame = [id: int]

scala> val e = sc.parallelize(List((1,2),(2,3),(4,5))).toDF("src","dst")
e: org.apache.spark.sql.DataFrame = [src: int, dst: int]

scala> val g = GraphFrame(v, e)
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term scalalogging in value com.typesafe,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.typesafe.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access type LazyLogging in value com.slf4j,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.slf4j.
```

**Comment by jkbradley** [comment] 2016-10-03 23:56
Whoops!  @thunterdb pointed out the solution: It's that you should include it using the ```--packages``` argument, not the ```--jars``` argument.  "jars" will not download the dependencies like scalalogging, whereas "packages" will.

```
bin/spark-shell --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11
```

It's actually noted on the page: [https://spark-packages.org/package/graphframes/graphframes]

I'll close this.

**Closed by jkbradley** 2016-10-03 23:56 UTC

**Comment by sbromberger** [comment] 2016-10-04 00:43
Wait a second - http://graphframes.github.io/quick-start.html needs to be updated, then. That's where I found the original instructions...

**Comment by sbromberger** [comment] 2016-10-04 16:28
This doesn't work:

```
spark-shell --master local[4] --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11 --jars ~/.m2/repository/com/typesafe/scala-logging//scala-logging-slf4j_2.11/2.1.2/scala-logging-slf4j_2.11-2.1.2.jar

...
scala> val g = GraphFrame(v.toDF("id"), e)
error: missing or invalid dependency detected while loading class file 'LazyLogging.class'.
```

**Comment by jkbradley** [comment] 2016-10-04 19:05
Oh thanks!  I'll update the quick start guide.

Does spark-shell work without the --jars argument, in which case I'd hope it would download the correct dependencies?

**Comment by sbromberger** [comment] 2016-10-04 19:12
> Does spark-shell work without the --jars argument, in which case I'd hope it would download the correct dependencies?

No (sorry for the complete paste, but I don't know what's significant in this output):

```
$ spark-shell --master local[4] --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11
Ivy Default Cache set to: /Users/me/.ivy2/cache
The jars for the packages stored in: /Users/me/.ivy2/jars
:: loading settings :: url = jar:file:/usr/local/Cellar/apache-spark/2.0.0/libexec/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found graphframes#graphframes;0.2.0-spark2.0-s_2.11 in local-m2-cache
:: resolution report :: resolve 228ms :: artifacts dl 6ms
	:: modules in use:
	graphframes#graphframes;0.2.0-spark2.0-s_2.11 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/7ms)
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
16/10/04 12:08:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/04 12:08:42 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Spark context Web UI available at http://127.0.0.1:4040
Spark context available as 'sc' (master = local[4], app id = local-1475608121881).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.0
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.graphframes.GraphFrame
import org.graphframes.GraphFrame

scala> import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.{SparkConf, SparkContext}

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> val sq = new SQLContext(sc)
warning: there was one deprecation warning; re-run with -deprecation for details
sq: org.apache.spark.sql.SQLContext = org.apache.spark.sql.SQLContext@13c90c06

scala> val v = sc.parallelize(List(1,2,3,4,5)).toDF("id")
v: org.apache.spark.sql.DataFrame = [id: int]

scala> val e = sc.parallelize(List((1,2),(2,3),(4,5))).toDF("src","dst")
e: org.apache.spark.sql.DataFrame = [src: int, dst: int]

scala> val g = GraphFrame(v, e)
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term scalalogging in value com.typesafe,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.typesafe.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access type LazyLogging in value com.slf4j,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.slf4j.
```

**Comment by sbromberger** [comment] 2016-10-04 19:16
If it makes a difference, we're using maven....

**Comment by jkbradley** [comment] 2016-10-04 21:15
I'll test with maven now.  It worked for me with sbt.

**Comment by jkbradley** [comment] 2016-10-04 21:36
Just tested with maven, and it worked for me.  The only difference in our outputs is with finding dependencies, where yours is pulling graphframes from local cache and mine appears to be tracing the dependencies further:

```
bin/spark-shell --master local[4] --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11
Ivy Default Cache set to: /Users/josephkb/.ivy2/cache
The jars for the packages stored in: /Users/josephkb/.ivy2/jars
:: loading settings :: url = jar:file:/Users/josephkb/spark/assembly/target/scala-2.11/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found graphframes#graphframes;0.2.0-spark2.0-s_2.11 in spark-packages
	found com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 in list
	found com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 in list
	found org.scala-lang#scala-reflect;2.11.0 in list
	[2.11.0] org.scala-lang#scala-reflect;2.11.0
	found org.slf4j#slf4j-api;1.7.7 in list
:: resolution report :: resolve 388ms :: artifacts dl 16ms
	:: modules in use:
	com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 from list in [default]
	com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 from list in [default]
	graphframes#graphframes;0.2.0-spark2.0-s_2.11 from spark-packages in [default]
	org.scala-lang#scala-reflect;2.11.0 from list in [default]
	org.slf4j#slf4j-api;1.7.7 from list in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   5   |   0   |   0   |   0   ||   5   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 5 already retrieved (0kB/10ms)
16/10/04 14:26:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/04 14:26:28 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Spark context Web UI available at http://192.168.2.196:4040
Spark context available as 'sc' (master = local[4], app id = local-1475616388222).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.2-SNAPSHOT
      /_/
         
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_80)
```

Could you please try removing graphframes from your local ivy cache?

**Comment by jkbradley** [comment] 2016-10-04 21:49
I just tried again using 2.0.0 (instead of 2.0.2-SNAPSHOT), and it worked for me.  So I bet it is an ivy cache issue.

**Comment by sbromberger** [comment] 2016-10-04 23:30
I did an `rm -rf ~/.ivy2/cache/graphframes` and reran - same issue:

```
$ spark-shell --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11
Ivy Default Cache set to: /Users/me/.ivy2/cache
The jars for the packages stored in: /Users/me/.ivy2/jars
:: loading settings :: url = jar:file:/usr/local/Cellar/apache-spark/2.0.0/libexec/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found graphframes#graphframes;0.2.0-spark2.0-s_2.11 in local-m2-cache
downloading file:/Users/me/.m2/repository/graphframes/graphframes/0.2.0-spark2.0-s_2.11/graphframes-0.2.0-spark2.0-s_2.11.jar ...
	[SUCCESSFUL ] graphframes#graphframes;0.2.0-spark2.0-s_2.11!graphframes.jar (2ms)
:: resolution report :: resolve 3821ms :: artifacts dl 4ms
	:: modules in use:
	graphframes#graphframes;0.2.0-spark2.0-s_2.11 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   1   |   1   |   0   ||   1   |   1   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/10ms)
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
16/10/04 16:26:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/04 16:26:54 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
16/10/04 16:26:55 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Spark context Web UI available at http://127.0.0.1:4041
Spark context available as 'sc' (master = local[*], app id = local-1475623615008).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.0
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_77)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> import org.graphframes.GraphFrame
import org.graphframes.GraphFrame

scala> import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.{SparkConf, SparkContext}

scala> val sq = new SQLContext(sc)
warning: there was one deprecation warning; re-run with -deprecation for details
sq: org.apache.spark.sql.SQLContext = org.apache.spark.sql.SQLContext@3c71cf3e

scala> val v = sc.parallelize(List(1,2,3,4,5)).toDF("id")
16/10/04 16:28:04 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/10/04 16:28:04 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
v: org.apache.spark.sql.DataFrame = [id: int]

scala> val e = sc.parallelize(List((1,2),(2,3),(4,5))).toDF("src","dst")
e: org.apache.spark.sql.DataFrame = [src: int, dst: int]

scala> val g = GraphFrame(v, e)
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term scalalogging in value com.typesafe,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.typesafe.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access type LazyLogging in value com.slf4j,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.slf4j.
```

**Comment by sbromberger** [comment] 2016-10-04 23:32
(I also tried removing the cache as well as the jar in `~/.ivy2/jars`. Same issue.)

**Comment by sbromberger** [comment] 2016-10-04 23:46
SOLVED. To fix:

1) removed ivy cache (`rm -rf ~/.ivy2/cache/graphframes`) and jar (`rm  ~/.ivy2/jars/graphframes*`)
2) removed maven repo files (`rm -rf ~/.m2/repository/graphframes`)
3) ran `spark-shell --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11`

Not sure how it found the package, but it works now. Thanks for your patience and help, @jkbradley !

**Comment by jkbradley** [comment] 2016-10-05 23:30
Phew!  Glad it worked and happy to help.  : )
