### ISSUE TITLE
is there a way to do incremental Connected Components?

### ISSUE THREAD

**Issue by kant777** [graphframes/graphframes#358] opened 2020-02-27 07:20 UTC
is there a way to do incremental Connected Components? 

For example say at time `t1` I have edges Dataset `DS1` for which I computed Connected Components `CC1`. Now say at time `t2` I have edges Dataset `DS2` which can connect to edges in `DS1` How can I make sure I dont recompute connected components on the whole graph every time? My graph is evolving over time so the number of edges and vertices are increasing over time.

**Comment by architch** [comment] 2020-03-21 11:58
There are some approaches I could figure out to implement incremental connected component for our use case:
**Approach 1:** Use the CC1 output as edges and append the new edges DS2 to these and run CC over this dataset , this will converge faster hence it should not take much time.
**Approach 2:** Find the distinct nodes from DS2 
Join these distinct nodes with CC1 to figure out all the connected components  in CC1 which relates to these delta nodes.
Now you have a smaller dataset to run connected component.(Worst case scenario, it might pick up full graph).
**Approach 3:(best one)** This is the one which gave good results and had to run CC over only the delta edges(small dataset):

1. Roll up delta edges(DS2) over labels assigned in CC1.
2. Run connected component over this rolled up data set (output CC2).
3. Explode the newly assigned labels in CC2 to assign it to all the historical nodes.
**Note: If historical edges are 10 and delta edges are 2 then Connected Component will run only on 2 edges(rolled up). Hence gives better performance.**
here is the implementation:
```
private def runDeltaCC(deltaEdges: DataFrame,histComponents: DataFrame): DataFrame={
  val rolledUpEdges=deltaEdges.join(histComponents,col(SRC)===col(ID),"left_outer")
    .select(coalesce(col(COMPONENT),col(SRC)).as(SRC),col(DST))
    .join(histComponents,col(DST)===col(ID),"left_outer")
    .select(col(SRC),coalesce(col(COMPONENT),col(DST)).as(DST))
  val deltaCCOut=GraphFrame.fromEdges(rolledUpEdges).connectedComponents.run()
  deltaCCOut.join(histComponents,histComponents(COMPONENT)===deltaCCOut(ID),"full_outer")
    .select(coalesce(histComponents(ID),deltaCCOut(ID)).as(ID),
      coalesce(deltaCCOut(COMPONENT),histComponents(COMPONENT)).as(COMPONENT))
}
```
I had run on data of around 2 billion nodes, 10 billion historical edges and daily 20-30 million delta edges and approach 3 worked best.

**Comment by amuraru** [comment] 2020-03-21 15:54
Would that work if edges in DS1 are removed? Ie not only additive edges

**Comment by architch** [comment] 2020-03-21 16:22
These approaches won’t work if edges are being removed as we are leveraging the output of previous runs. 
Only solution is to run on all the edges of they are being removed.

**Comment by kant777** [comment] 2020-03-22 08:55
@architch Thanks a lot for this. I ended up with approach #1 :) but I like approach #3 so I will change mine to approach #3.

How long does it take you to run 20-30 million delta edges?

**Comment by architch** [comment] 2020-03-22 10:13
It tool less than 20 min with approach three on above mentioned dataset which is significantly less when running CC on full dataset (around 1.5 hrs).

**Closed** 2020-03-22 10:22 UTC

**Comment by entimaniac** [comment] 2024-06-04 15:37
> These are some approaches I could figure out to implement incremental connected component for our use case: **Approach 1:** Use the CC1 output as edges and append the new edges DS2 to these and run CC over this dataset , this will converge faster hence it should not take much time. **Approach 2:** Find the distinct nodes from DS2 Join these distinct nodes with CC1 to figure out all the connected components in CC1 which relates to these delta nodes. Now you have a smaller dataset to run connected component.(Worst case scenario, it might pick up full graph). **Approach 3:(best one)** This is the one which gave good results and had to run CC over only the delta edges(smaller dataset):
> 
> 1. Roll up delta edges(DS2) over labels assigned in CC1.
> 2. Run connected component over this rolled up data set (output CC2).
> 3. Explode the newly assigned labels in CC2 to assign it to all the historical nodes.
>    **Note: If historical edges are 10 and delta edges are 2 then Connected Component will run only on 2 edges(rolled up). Hence gives better performance.**
>    here is the implementation:
> 
> ```
> private def runDeltaCC(deltaEdges: DataFrame,histComponents: DataFrame): DataFrame={
>   val rolledUpEdges=deltaEdges.join(histComponents,col(SRC)===col(ID),"left_outer")
>     .select(coalesce(col(COMPONENT),col(SRC)).as(SRC),col(DST))
>     .join(histComponents,col(DST)===col(ID),"left_outer")
>     .select(col(SRC),coalesce(col(COMPONENT),col(DST)).as(DST))
>   val deltaCCOut=GraphFrame.fromEdges(rolledUpEdges).connectedComponents.run()
>   deltaCCOut.join(histComponents,histComponents(COMPONENT)===deltaCCOut(ID),"full_outer")
>     .select(coalesce(histComponents(ID),deltaCCOut(ID)).as(ID),
>       coalesce(deltaCCOut(COMPONENT),histComponents(COMPONENT)).as(COMPONENT))
> }
> ```
> 
> I had run on data of around 2 billion nodes, 10 billion historical edges and daily 20-30 million delta edges and approach 3 worked best.

I love this so much and have adapted it for pyspark. Thank you so much for sharing. But there are some bugs may come up with this approach that need some additional code to resolve. Granted, I don't know if scala handles things very differently than pyspark, but the key issue I found was that I was getting unrelated nodes grouped into the same component after iterating. The cause of this is the component IDs generated overlap and are reused between runs frequently. Imagine day 1 that a component is given the ID of "10" and the next day no new IDs were linked to that component so no IDs from that old component are in the list to be processed on the new run. The new run may very well generate another component with ID of "10" and when the two groups are joined back together, we now have 2 distinct components with the same ID. And then analyzing the full data shows that individual nodes are related when they really aren't.  The fix for this for me is to generate a UUID per iteration and append that to the component. This way 2 runs generating the same component ID are very very unlikely to also have a duplicated UUID.  So "721554506483" becomes "efda0e64-ac3c-44cc-88ed-6b0e99e3d9a7_721554506483".

Here is my version in pyspark. I'm sure it can be cleaned up considerably:

```
def incremental_components(new_edges, existing_components):
  ### translated from:
  ### https://github.com/graphframes/graphframes/issues/358

  ### replace previously processed ids with existing component values
  new_edges = new_edges.join(existing_components, new_edges["src"] == existing_components["id"], "left_outer") \
    .select(coalesce(col("component"), col("src")).alias("src"), col("dst")).distinct() \
    .join(existing_components, col("dst") == col("id"), "left_outer") \
    .select(col("src"), coalesce(col("component"), col("dst")).alias("dst")).distinct()
  # ids from the "new data" that matched with the existing components/ids are now replaced with existing component values
  # Compute new components values for new data and repeated components 
  new_components = GraphFrame(from_edges(new_edges), new_edges).connectedComponents()
  new_components = new_components.withColumnRenamed("id","new_id").withColumnRenamed("component","new_component") # eliminate ambiguity during join
  prefix = str(uuid.uuid4()) + "_"
  new_components = new_components.withColumn("new_component", concat(lit(prefix), col("new_component")))

  # join both sets of IDs, explodes the swapped components with the original IDs
  full_components = new_components.join(existing_components, existing_components["component"] == new_components["new_id"], "full_outer") 
  full_components = full_components.select(coalesce(full_components["id"], full_components["new_id"]).alias("id"), coalesce(full_components["new_component"], full_components["component"]).alias("component"))
  full_components = full_components.distinct() 
  return full_components
```
